<?php

use Drupal\diff\Routing\DiffRouteProvider;

/**
 * Implements hook_entity_type_alter().
 */
function diff_test_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityType $entity_type */
  $entity_type = $entity_types['entity_test_rev'];
  $handlers = $entity_type->get('handlers');
  $handlers['route_provider']['html_diff'] = DiffRouteProvider::class;
  $entity_type->set('handlers', $handlers);
  $entity_type->setLinkTemplate('revisions-diff', "/entity_test_rev/{entity_test_rev}/revision/{left_revision}/{right_revision}");
}
